# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Master
        uses: actions/checkout@v6.0.2
        with:
          ref: master
      - name: Checkout Dev Branch
        run: | 
          git fetch --depth=1 origin dev
          git worktree add branch/dev dev
      - name: Checkout 2019 bingo as a branch
        run: |
          git fetch --depth=1 origin 7f4e4e83d8c11f05f77870a6223783d104bdc77e
          git worktree add branch/2019 7f4e4e83d8c11f05f77870a6223783d104bdc77e
      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
